In [1]:
import pandas as pd

In [6]:
url ="https://en.wikipedia.org/wiki/List_of_cities_in_Gujarat_by_population"

In [7]:
data =pd.read_html(url)

In [8]:
type(data)

list

In [9]:
len(data)

3

In [13]:
data=pd.read_html(url)

In [14]:
data[0]

,Unnamed: 0,City,District,Area,Population (2021),Population (2011)
0,1.0,Ahmedabad,Ahmedabad,505.00,8253000,6357693
1,2.0,Surat,Surat,461.60,6936534,4645384
2,3.0,Vadodara,Vadodara,454.33,5240522,3022221
3,4.0,Rajkot,Rajkot,170.00,1934000,1390640
4,5.0,Bhavnagar,Bhavnagar,108.27,712000,605882
5,6.0,Jamnagar,Jamnagar,125.67,711000,600934
6,7.0,Gandhinagar,Gandhinagar,326.00,410323,206167
7,8.0,Junagadh,Junagadh,160.00,407000,319462
8,9.0,Gandhidham,Kutch,63.49,406000,247992
9,10.0,Anand,Anand,47.89,385291,288092
10,11.0,Navsari,Navsari,43.71,367322,292719
11,12.0,Morbi,Morbi,46.58,360001,251859
12,13.0,Nadiad,Kheda,45.16,330400,225071
13,14.0,Surendranagar,Surendranagar,58.60,298692,253606
14,15.0,Bharuch,Bharuch,43.80,288244,223647
15,16.0,Mehsana,Mehsana,31.76,257043,190753
16,17.0,Bhuj,Kutch,56.00,251489,219514
17,18.0,Porbandar,Porbandar,38.43,243584,217203
18,19.0,Palanpur,Banaskantha,39.50,242936,141532
19,20.0,Valsad,Valsad,24.10,231756,170060
20,21.0,Vapi,Valsad,22.44,230598,163630
21,22.0,Gondal,Rajkot,74.48,189797,173353
22,23.0,Veraval,Gir Somnath,39.95,185797,156696
23,24.0,Godhra,Panchmahal,20.16,173014,143644
24,25.0,Patan,Patan,112.84,171614,133744
25,26.0,Kalol,Gandhinagar,25.42,171395,133737
26,27.0,Dahod,Dahod,14.00,159326,130505
27,28.0,Botad,Botad,10.36,158985,130327
28,29.0,Amreli,Amreli,65.00,146014,117967
29,30.0,Deesa,Banaskantha,20.81,135869,111160
30,31.0,Jetpur,Rajkot,36.00,129653,118302

In [16]:
# inplace of one line 
data=pd.read_html(url)[0]
data

,Unnamed: 0,City,District,Area,Population (2021),Population (2011)
0,1.0,Ahmedabad,Ahmedabad,505.00,8253000,6357693
1,2.0,Surat,Surat,461.60,6936534,4645384
2,3.0,Vadodara,Vadodara,454.33,5240522,3022221
3,4.0,Rajkot,Rajkot,170.00,1934000,1390640
4,5.0,Bhavnagar,Bhavnagar,108.27,712000,605882
5,6.0,Jamnagar,Jamnagar,125.67,711000,600934
6,7.0,Gandhinagar,Gandhinagar,326.00,410323,206167
7,8.0,Junagadh,Junagadh,160.00,407000,319462
8,9.0,Gandhidham,Kutch,63.49,406000,247992
9,10.0,Anand,Anand,47.89,385291,288092
10,11.0,Navsari,Navsari,43.71,367322,292719
11,12.0,Morbi,Morbi,46.58,360001,251859
12,13.0,Nadiad,Kheda,45.16,330400,225071
13,14.0,Surendranagar,Surendranagar,58.60,298692,253606
14,15.0,Bharuch,Bharuch,43.80,288244,223647
15,16.0,Mehsana,Mehsana,31.76,257043,190753
16,17.0,Bhuj,Kutch,56.00,251489,219514
17,18.0,Porbandar,Porbandar,38.43,243584,217203
18,19.0,Palanpur,Banaskantha,39.50,242936,141532
19,20.0,Valsad,Valsad,24.10,231756,170060
20,21.0,Vapi,Valsad,22.44,230598,163630
21,22.0,Gondal,Rajkot,74.48,189797,173353
22,23.0,Veraval,Gir Somnath,39.95,185797,156696
23,24.0,Godhra,Panchmahal,20.16,173014,143644
24,25.0,Patan,Patan,112.84,171614,133744
25,26.0,Kalol,Gandhinagar,25.42,171395,133737
26,27.0,Dahod,Dahod,14.00,159326,130505
27,28.0,Botad,Botad,10.36,158985,130327
28,29.0,Amreli,Amreli,65.00,146014,117967
29,30.0,Deesa,Banaskantha,20.81,135869,111160
30,31.0,Jetpur,Rajkot,36.00,129653,118302

In [17]:
# list of banks in india
url="https://en.wikipedia.org/wiki/List_of_banks_in_India"

In [21]:
data = pd.read_html(url)[2]
data

,State,Bank's Name,Established,Headquarters,Branches,Sponsor Bank,Refs
0,Andhra Pradesh,Andhra Pradesh Grameena Vikas Bank,2006,"Warangal, Telangana",755,State Bank of India,NaN
1,Andhra Pradesh,Andhra Pragathi Grameena Bank,2006,"Kadapa, Andhra Pradesh",552,Canara Bank,NaN
2,Andhra Pradesh,Chaitanya Godavari Gramin Bank[51],2006,"Guntur, Andhra Pradesh",219,Union Bank of India,NaN
3,Andhra Pradesh,Saptagiri Gramin Bank[52],2006,"Chittoor, Andhra Pradesh",220,Indian Bank,NaN
4,Arunachal Pradesh,Arunachal Pradesh Rural Bank[53],1983,"Itanagar, Arunachal Pradesh",30,State Bank of India,NaN
5,Assam,Assam Gramin Vikash Bank,2006,"Guwahati, Assam",474,Punjab National Bank,NaN
6,Bihar,Dakshin Bihar Gramin Bank,2019,"Patna, India",1078,Punjab National Bank,NaN
7,Bihar,Uttar Bihar Gramin Bank,2008,"Muzaffarpur, India",1032,Central Bank of India,[54]
8,Chhattisgarh,Chhattisgarh Rajya Gramin Bank[55],2013,"Raipur, Chhattisgarh",625,State Bank of India,[56]
9,Gujarat,Baroda Gujarat Gramin Bank,2019,"Vadodara, Gujarat",489,Bank of Baroda,[57]
10,Gujarat,Saurashtra Gramin Bank[58],1978,"Rajkot, Gujarat",259,State Bank of India,[59]
11,Haryana,Sarva Haryana Gramin Bank[60],2013,"Rohtak, Haryana",542,Punjab National Bank,NaN
12,Himachal Pradesh,Himachal Pradesh Gramin Bank,2013,"Mandi, Himachal Pradesh",265,Punjab National Bank,[61]
13,Jammu And Kashmir,Ellaquai Dehati Bank,1979,"Srinagar, Jammu and Kashmir",116,State Bank of India,NaN
14,Jammu And Kashmir,Jammu And Kashmir Grameen Bank,2009,"Jammu, Jammu and Kashmir",217,Jammu & Kashmir Bank,NaN
15,Jharkhand,Jharkhand Rajya Gramin Bank,2019,"Ranchi, Jharkhand",443,State Bank Of India,NaN
16,Karnataka,Karnataka Gramin Bank,2019,"Ballari, Karnataka",1142,Canara Bank,NaN
17,Karnataka,Karnataka Vikas Grameena Bank,2005,"Dharwad, Karnataka",633,Canara Bank,NaN
18,Kerala,Kerala Gramin Bank,2013,"Malappuram, Kerala",634,Canara Bank,[62]
19,Madhya Pradesh,Madhya Pradesh Gramin Bank,2019,"Indore, Madhya Pradesh",866,Bank of India,NaN
20,Madhya Pradesh,Madhyanchal Gramin Bank,2012,"Sagar, Madhya Pradesh",454,State Bank of India,NaN
21,Maharashtra,Maharashtra Gramin Bank,2008,"Aurangabad, Maharashtra",391,Bank of Maharashtra,NaN
22,Maharashtra,Vidarbha Konkan Gramin Bank[63],2013,"Nagpur, Maharashtra",318,Bank of India,NaN
23,Manipur,Manipur Rural Bank,1981,"Imphal, Manipur",28,Punjab National Bank,NaN
24,Meghalaya,Meghalaya Rural Bank,1981,"Shillong, Meghalaya",87,State Bank of India,[64]
25,Mizoram,Mizoram Rural Bank,1983,"Aizawl, Mizoram",85,State Bank of India,NaN
26,Nagaland,Nagaland Rural Bank,1983,"Kohima, Nagaland",10,State Bank of India,NaN
27,Odisha,Odisha Gramya Bank,2013,"Bhubaneswar, India",549,Indian Overseas Bank,NaN
28,Odisha,Utkal Grameen Bank,2012,"Bolangir, Odisha",442,State Bank of India,NaN
29,Puducherry,Puduvai Bharathiar Grama Bank,2008,"Pondicherry, Puducherry",43,Indian Bank,NaN
30,Punjab,Punjab Gramin Bank,2019,"Kapurthala, Punjab",419,Punjab National Bank,NaN
31,Rajasthan,Rajasthan Marudhara Gramin Bank,2014,"Jodhpur, Rajasthan",715,State Bank of India,NaN
32,Rajasthan,Baroda Rajasthan Kshetriya Gramin Bank,2013,"Ajmer, Rajasthan",833,Bank of Baroda,[65]
33,Tamil Nadu,Tamil Nadu Grama Bank,2019,"Salem, Tamil Nadu",630,Indian Bank,NaN
34,Telangana,Telangana Grameena Bank,2014,"Hyderabad, Telangana",421,State Bank of India,[66]
35,Tripura,Tripura Gramin Bank,1976,"Agartala, India",142,Punjab National Bank,NaN
36,Uttar Pradesh,Aryavart Bank,2019,"Lucknow, Uttar Pradesh",1365,Bank of India,NaN
37,Uttar Pradesh,Baroda UP Bank,2020,"Ayodhya, Uttar Pradesh",2050,Bank of Baroda,NaN
38,Uttar Pradesh,Prathama UP Gramin Bank,2019,"Moradabad, Uttar Pradesh",938,Punjab National Bank,NaN
39,Uttarakhand,Uttarakhand Gramin Bank,2012,"Dehradun, Uttarakhand",286,State Bank of India,[67]
40,West Bengal,Bangiya Gramin Vikash Bank,2007,"Berhampore, West Bengal",587,Punjab National Bank,NaN
41,West Bengal,Paschim Banga Gramin Bank,2007,"Howrah, West Bengal",230,UCO Bank,NaN
42,West Bengal,Uttarbanga Kshetriya Gramin Bank,1977,"Coochbehar, West Bengal",142,Central Bank of India,NaN